# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Install required tools
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.401'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

### BackEnd Rest API build and test
- script: |
    cd './RestApi/Sepes.RestApi'
    dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'RestApi/**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

### FrontEnd test and build
- script: |
    cd FrontEnd
    npm install
    CI=true npm test
    npm run build
  displayName: 'npm install and build'